name: dotnet package

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout dependencies
        run: |
          git clone git@github.com:dkavolis/ksp_binaries.git ${{ github.workspace }}/b

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: |
          cp "${{ github.workspace }}/.github/package.build.props" "${{ github.workspace }}/Directory.Build.props.user"
          cp "${{ github.workspace }}/.github/package.config.json" "${{ github.workspace }}/config.json.user"
          msbuild /p:Configuration=Release ${{ github.workspace }}/FerramAerospaceResearch.sln -m

      - name: Package
        id: package-mod
        run: |
          echo "::set-output name=archive::$(python -m buildtools package)"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FerramAerospaceResearch-${{ github.sha }}
          path: ${{ steps.package-mod.outputs.archive }}
